---
title: "Finalized Plots"
output: html_notebook
---

```{r}
library(tidyverse) #For dplyr and data sorting
library(ggplot2) #For plotting
library(bbmle) #For ICtab
library(car) #For Anova
library(forcats) #For Factor Work
library(ggpubr) #For the significance bars
```



### Functions and Varibles I need
```{r}
rad2deg <- function(rad) {(rad * 180) / (pi)}
deg2rad <- function(deg) {(deg * pi) / (180)}
round_any <- function(x, accuracy, f=round){f(x/ accuracy) * accuracy}
ang_mean <- function(x){rad2deg(atan2(mean(sin(deg2rad(x))),mean(cos(deg2rad(x)))))}

fold_angle_0_360_to_0_180 <- function(x){abs(abs(x-180)-180)}

fold_angle_neg_180_180_to_neg_90_90 <- function(x){ifelse(x > 90,90-abs(90-x),ifelse(x < -90, -90+abs(-90-x), x))}

min_n <- function(x,n){sort(x)[1:n]}
max_n <- function(x,n){sort(x,decreasing = TRUE)[1:n]}

light_no_ab_color = "#d4d7dd"
light_ab_color = "#f5ba9e"
dark_no_ab_color = "#5e94d4"
sim_color = "#777777"

flow_split_still = "#F59DE2"
flow_split_flow = "#5DD492"

dark_split_light = "#E71D36"
dark_split_dark = "#011627"

tailbeat_len = 19

allowed_flow_type = c("Still Water","Flowing Water (2 BL/s)")
```


### NND

```{r}
school_data <- read.csv("Fish_School_Values.csv")
school_data <- na.omit(school_data)

school_data <- school_data %>% mutate(Flow = ifelse(Flow == "0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation == "N", "No Ablation", "Ablated")) %>%
                           mutate(Darkness = ifelse(Darkness == "N", "Light", "Dark")) %>%
                           filter(School_Speed < 7) %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Still Water","Flowing Water (2 BL/s)"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark"))) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep=", "))) %>%
                           filter(Flow %in% allowed_flow_type)
```


```{r}
my_comparisons <- list( c("No Ablation, Light", "No Ablation, Dark"))

ggplot(school_data, aes(x = interaction(Ablation,Darkness,sep=", "), y = NND, fill = interaction(Ablation,Darkness,sep=", ")))+
  geom_boxplot(outlier.shape = NA) +
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  ggtitle("Effect of Available Senses on Nearest Neighbor Distance (NND)") +
  xlab("") +
  ylab("NND (BL)") +
  theme_light() +
  facet_wrap(~ Flow, strip.position = "bottom")+
  #stat_compare_means(aes(label = ..p.signif..), method = "t.test", ref.group = "Flow 0, No Ablation, Light")
  stat_compare_means(comparisons = my_comparisons, label.y = c(2.5), label = "p.signif", hide.ns = TRUE) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggsave("Final Graphs/School_NND.png")
```

### Num fish Within 2 BL

```{r}
raw_school_data <- read.csv("Fish_Raw_Comp_Values.csv")
raw_school_data <- na.omit(raw_school_data)

raw_school_data <- raw_school_data %>% mutate(Flow = ifelse(Flow == "0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation == "N", "No Ablation", "Ablated")) %>%
                           mutate(Darkness = ifelse(Darkness == "N", "Light", "Dark")) %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Still Water","Flowing Water (2 BL/s)"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark"))) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep=", "))) %>%
                           separate(Fish, c("Fish1", "Fish2"),sep="x") %>%
                           filter(Flow %in% allowed_flow_type)

raw_school_data_fish_switch <- raw_school_data %>% mutate(Fish3 = Fish1) %>%
                                                   mutate(Fish1 = Fish2) %>%
                                                   mutate(Fish2 = Fish3) %>%
                                                   select(-c(Fish3))

raw_school_data_both_fish <- bind_rows(raw_school_data, raw_school_data_fish_switch)

count_within_2 <- raw_school_data_both_fish %>% mutate(Tailbeat = round_any(Frame_Num, tailbeat_len)/tailbeat_len+1) %>%
                                                group_by(Year, Month, Day, Trial, Flow, Ablation, Darkness, Tailbeat, Frame_Num, Fish1) %>%
                                                summarise(Count_Fish_in_2BL = sum(Distance <= 2)) %>%
                                                ungroup() %>%
                                                group_by(Year, Month, Day, Trial, Flow, Ablation, Darkness, Tailbeat) %>%
                                                summarise(Mean_Count_Fish_in_2BL = mean(Count_Fish_in_2BL)) %>%
                                                ungroup()
```


```{r}
my_comparisons <- list( c("No Ablation, Light", "No Ablation, Dark"), c("No Ablation, Light", "Ablated, Light") )

ggplot(count_within_2, 
       aes(x = interaction(Ablation,Darkness,sep=", "), y = Mean_Count_Fish_in_2BL+1,
           fill = interaction(Ablation,Darkness,sep=", ")))+
  geom_boxplot(outlier.shape = NA) +
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  ggtitle("Mean size of group within 2BL") +
  xlab("") +
  ylab("Mean size of group within 2BL (# of Fish)") +
  ylim(0,9) +
  theme_light() +
  facet_wrap(~ Flow, strip.position = "bottom")+
  #stat_compare_means(aes(label = ..p.signif..), method = "t.test", ref.group = "Flow 0, No Ablation, Light")
  stat_compare_means(comparisons = my_comparisons, label.y = c(7.5,8.5), label = "p.signif", hide.ns = TRUE) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  scale_y_continuous(breaks=c(0,2,4,6,8))

ggsave("Final Graphs/Mean_Group_Size.png")
```

### Polarization

```{r}
school_data <- read.csv("Fish_School_Values.csv")
school_data <- na.omit(school_data)

school_data <- school_data %>% mutate(Flow = ifelse(Flow == "0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation == "N", "No Ablation", "Ablated")) %>%
                           mutate(Darkness = ifelse(Darkness == "N", "Light", "Dark")) %>%
                           filter(School_Speed < 7) %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Still Water","Flowing Water (2 BL/s)"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark"))) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep=", "))) %>% 
                           filter(Flow %in% allowed_flow_type)
```

```{r}
ggplot(school_data, aes(x = interaction(Ablation,Darkness,sep=", "), y = School_Polar, fill = interaction(Ablation,Darkness,sep=", ")))+
  geom_boxplot(outlier.shape = NA) +
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  ggtitle("Effect of Available Senses on School Polarization") +
  xlab("") +
  ylab("Polarization") +
  theme_light() +
  facet_wrap(~ Flow, strip.position = "bottom")+
  #stat_compare_means(aes(label = ..p.signif..), method = "t.test", ref.group = "Flow 0, No Ablation, Light")
  #stat_compare_means(comparisons = my_comparisons, label.y = c(1, 1.25), label = "p.signif", hide.ns = TRUE) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggsave("Final Graphs/Polarization.png")
```

### Number of fish aligned within 2 BL

```{r}
count_within_2_aligned <- raw_school_data_both_fish %>% mutate(Tailbeat = round_any(Frame_Num, tailbeat_len)/tailbeat_len+1) %>%
                                                        filter(Heading_Diff > -30 & Heading_Diff < 30) %>%
                                                        group_by(Year, Month, Day, Trial, Flow, Ablation, Darkness, Tailbeat, Frame_Num, Fish1) %>%
                                                        summarise(Count_Fish_in_2BL = sum(Distance <= 2)) %>%
                                                        ungroup() %>%
                                                        group_by(Year, Month, Day, Trial, Flow, Ablation, Darkness, Tailbeat) %>%
                                                        summarise(Mean_Count_Fish_in_2BL = mean(Count_Fish_in_2BL)) %>%
                                                        ungroup()
```

```{r}
my_comparisons <- list( c("No Ablation, Light", "No Ablation, Dark"), c("No Ablation, Light", "Ablated, Light") )

ggplot(count_within_2_aligned, 
       aes(x = interaction(Ablation,Darkness,sep=", "), y = Mean_Count_Fish_in_2BL+1,
           fill = interaction(Ablation,Darkness,sep=", ")))+
  geom_boxplot(outlier.shape = NA) +
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  ggtitle("Mean size of group within 2BL") +
  xlab("") +
  ylab("Number of Aligned Fish within 2BL (# of Fish)") +
  ylim(0,5) +
  theme_light() +
  facet_wrap(~ Flow, strip.position = "bottom")+
  #stat_compare_means(aes(label = ..p.signif..), method = "t.test", ref.group = "Flow 0, No Ablation, Light")
  stat_compare_means(comparisons = my_comparisons, label.y = c(3.5,4.25), label = "p.signif", hide.ns = TRUE) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  scale_y_continuous(breaks=c(0,2,4,6,8))

ggsave("Final Graphs/Num_Aligned_Fish_2BL.png")

```


### Speed Ratio

```{r}
speed_whole_school <- school_data

indiv_data <- read.csv("Fish_Individual_Values.csv")
indiv_data <- na.omit(indiv_data)

indiv_data <- indiv_data %>% mutate(Flow = ifelse(Flow == "0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                             mutate(Ablation = ifelse(Ablation == "N", "No Ablation", "Ablated")) %>%
                             mutate(Darkness = ifelse(Darkness == "N", "Light", "Dark")) %>%
                             mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Still Water","Flowing Water (2 BL/s)"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark"))) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep=", "))) %>%
                           filter(Flow %in% allowed_flow_type)

indiv_data_4_speed <- indiv_data %>% group_by(Year, Month, Day, Trial, Tailbeat_Num) %>%
                                     summarise(Mean_Speed = mean(Speed))

fish_speed_division <- speed_whole_school %>% inner_join(indiv_data_4_speed, by = c("Year", "Month", "Day", "Trial", "Tailbeat_Num")) %>%
                                              mutate(Divided_Speed = School_Speed/Mean_Speed)
```

```{r}
my_comparisons <- list( c("No Ablation, Light", "No Ablation, Dark"), c("No Ablation, Light", "Ablated, Light") )

ggplot(fish_speed_division, aes(x = interaction(Ablation,Darkness,sep=", "), y = Divided_Speed, fill = interaction(Ablation,Darkness,sep=", ")))+
  geom_boxplot(outlier.shape = NA) +
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  ggtitle("Effect of Available Senses on School Speed") +
  xlab("") +
  ylab("Speed (BL/s)") +
  ylim(0,8) +
  theme_light() +
  facet_wrap(~ Flow, strip.position = "bottom")+
  #stat_compare_means(aes(label = ..p.signif..), method = "t.test", ref.group = "Flow 0, No Ablation, Light")
  stat_compare_means(comparisons = my_comparisons, label.y = c(6.5,7.5), label = "p.signif", hide.ns = TRUE) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggsave("Final Graphs/School_Speed_Over_Indiv_Speed.png")

```

### Turning Bias

```{r}
turning_data <- read.csv("Annushka_Turning_Data_Wall.csv") %>%
                           filter(Next.to.Wall == 0) %>%
                           mutate(Flow = ifelse(Flow == "F0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation %in% c("LN","TN"), "No Ablation", "Ablated")) %>%
                           mutate(Darkness = ifelse(Darkness == "DN", "Light", "Dark")) %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Still Water","Flowing Water (2 BL/s)"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark"))) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep=", "))) %>%
                           mutate(Fish_Num_Ratio = No..Fish.Right/8) %>%
                           mutate(Fish_Ratio = paste(No..Fish.Left,No..Fish.Right,sep=":")) %>%
                           filter(Fish_Ratio %in% c("7:0","6:1","5:2","4:3","3:4","2:5","1:6","0:7")) %>%
                           mutate(Fish_Ratio = fct_relevel(Fish_Ratio,
                                                           c("7:0","6:1","5:2","4:3",
                                                             "3:4","2:5","1:6","0:7"))) %>%
                           mutate(turn_bool = ifelse(Turn.Direction == "right",1,0)) %>%
                           filter(Flow %in% allowed_flow_type)

turning_data_sum <- turning_data %>% na.omit %>%
                                     group_by(Fish_Ratio,Fish_Num_Ratio,Flow,Ablation,Darkness,Flow_Ablation_Darkness) %>%
                                     summarize(mean_right_turn = mean(turn_bool),
                                               sd_right_turn = sd(turn_bool),
                                               n = n()) %>%
                                     ungroup()

turning_data_sum_one <- turning_data %>% na.omit %>%
                                     group_by(Fish_Ratio,Fish_Num_Ratio) %>%
                                     summarize(mean_right_turn = mean(turn_bool),
                                               sd_right_turn = sd(turn_bool),
                                               n = n()) %>%
                                     ungroup()
```

```{r}
ggplot(turning_data_sum, aes(x = Fish_Num_Ratio, y = mean_right_turn, color = Flow))+
  geom_point()+
  geom_line(alpha = 0.25) +
  facet_wrap(~ Darkness + Ablation) +
  theme_classic() +
  xlab("# Fish on Left : # Fish on Right") +
  ylab("Probability of a Right Turn") +
  scale_colour_manual(values = c(light_ab_color,dark_no_ab_color)) +
  scale_x_continuous(breaks = c(0,0.125,0.25,0.375,
                                0.5,0.625,0.75,0.875),
                     labels = c("7:0","6:1","5:2","4:3",
                                "3:4","2:5","1:6","0:7"))

ggsave("Final Graphs/Right_Turn_Prob.png")
```

```{r}
#mi_fr_d <- glm(turn_bool ~ Fish_Num_Ratio * Darkness, data = turning_data, family = binomial)

mi_fr_fl_a <- glm(turn_bool ~ Fish_Num_Ratio*Flow*Ablation, data = turning_data, family = binomial)

ggplot(turning_data, aes(x = Fish_Num_Ratio, y = turn_bool, color = Ablation))+
  geom_jitter(alpha = 0.1, height = 0.025)+
  geom_line(aes(x = Fish_Num_Ratio, y = predict(mi_fr_fl_a, type="response"), color = Ablation, shape = Flow)) +
  geom_point(aes(x = Fish_Num_Ratio, y = predict(mi_fr_fl_a, type="response"), color = Ablation, shape = Flow)) +
  theme_classic() +
  xlab("# Fish on Left : # Fish on Right") +
  ylab("Probability of a Right Turn") +
  scale_colour_manual(values = c(light_ab_color,dark_no_ab_color,light_ab_color,dark_no_ab_color)) +
  scale_x_continuous(breaks = c(0,0.125,0.25,0.375,
                                0.5,0.625,0.75,0.875),
                     labels = c("7:0","6:1","5:2","4:3",
                                "3:4","2:5","1:6","0:7"))

ggsave("Final Graphs/Best_Model_Right_Turn_Prob.png")

```


### Simulated # of fish within 2 BL

```{r}
raw_school_data_simul <- rbind(read.csv("Fish_Raw_Comp_Values.csv"),
                               read.csv("Data Sim/Fish_Raw_Comp_Values_Random.csv"))
raw_school_data_simul <- na.omit(raw_school_data_simul) %>% filter(Flow == "0")

raw_school_data_simul <- raw_school_data_simul %>% mutate(Flow = ifelse(Flow == "0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation == "N", "No Ablation", ifelse(Ablation == "Y","Ablated","Simulated"))) %>%
                           mutate(Darkness = ifelse(Darkness == "N", "Light", ifelse(Darkness == "Y", "Dark", "Simulated"))) %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Still Water"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated","Simulated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark","Simulated"))) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep=", "))) %>%
                           separate(Fish, c("Fish1", "Fish2"),sep="x")

raw_school_data_simul_fish_switch <- raw_school_data_simul %>% mutate(Fish3 = Fish1) %>%
                                                   mutate(Fish1 = Fish2) %>%
                                                   mutate(Fish2 = Fish3) %>%
                                                   select(-c(Fish3))

raw_school_data_simul_both_fish <- bind_rows(raw_school_data_simul, raw_school_data_simul)

count_within_2_simul <- raw_school_data_simul_both_fish %>% mutate(Tailbeat = round_any(Frame_Num, tailbeat_len)/tailbeat_len+1) %>%
                                                group_by(Year, Month, Day, Trial, Flow, Ablation, Darkness, Tailbeat, Frame_Num, Fish1) %>%
                                                summarise(Count_Fish_in_2BL = sum(Distance <= 2)) %>%
                                                ungroup() %>%
                                                group_by(Year, Month, Day, Trial, Flow, Ablation, Darkness, Tailbeat) %>%
                                                summarise(Mean_Count_Fish_in_2BL = mean(Count_Fish_in_2BL)) %>%
                                                ungroup()
```

```{r}
my_comparisons <- list( c("No Ablation, Light", "No Ablation, Dark"),
                        c("No Ablation, Light", "Ablated, Light"),
                        c("No Ablation, Dark", "Simulated, Simulated"))

ggplot(count_within_2_simul %>% filter(Flow == "Still Water"),
       aes(x = interaction(Ablation,Darkness,sep=", "), y = Mean_Count_Fish_in_2BL+1,
           fill = interaction(Ablation,Darkness,sep=", ")))+
  geom_boxplot(outlier.shape = NA) +
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color,sim_color)) +
  ggtitle("Mean size of group within 2BL") +
  xlab("") +
  ylab("Mean size of group within 2BL (# of Fish)") +
  ylim(0,9) +
  theme_light() +
  facet_wrap(~ Flow, strip.position = "bottom")+
  #stat_compare_means(aes(label = ..p.signif..), method = "t.test", ref.group = "Flow 0, No Ablation, Light")
  stat_compare_means(comparisons = my_comparisons, label.y = c(7.5,8.5,6), label = "p.signif", hide.ns = TRUE) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  scale_y_continuous(breaks=c(0,2,4,6,8))

ggsave("Final Graphs/Simmed_Group_Num_in_2_BL.png")

```

### Simluated Data Aligned within 2BL

```{r}

max_offset <- 15

count_within_2_simul_aligned <- raw_school_data_simul_both_fish %>% mutate(Tailbeat = round_any(Frame_Num, tailbeat_len)/tailbeat_len+1) %>%
                                                        filter(abs(Heading_Diff) < max_offset) %>%
                                                        group_by(Year, Month, Day, Trial, Flow, Ablation, Darkness, Tailbeat, Frame_Num, Fish1) %>%
                                                        summarise(Count_Fish_in_2BL = sum(Distance <= 2)) %>%
                                                        ungroup() %>%
                                                        group_by(Year, Month, Day, Trial, Flow, Ablation, Darkness, Tailbeat) %>%
                                                        summarise(Mean_Count_Fish_in_2BL = mean(Count_Fish_in_2BL)) %>%
                                                        ungroup()
```

```{r}
my_comparisons <- list( c("No Ablation, Light", "No Ablation, Dark"),
                        c("No Ablation, Light", "Ablated, Light"),
                        c("No Ablation, Dark", "Simulated, Simulated"))

ggplot(count_within_2_simul_aligned %>% filter(Flow == "Still Water"), 
       aes(x = interaction(Ablation,Darkness,sep=", "), y = Mean_Count_Fish_in_2BL,
           fill = interaction(Ablation,Darkness,sep=", ")))+
  geom_boxplot(outlier.shape = NA) +
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color,sim_color)) +
  ggtitle("Mean size of group within 2BL") +
  xlab("") +
  ylab("Number of Aligned Fish within 2BL (# of Fish)") +
  theme_light() +
  facet_wrap(~ Flow, strip.position = "bottom")+
  #stat_compare_means(aes(label = ..p.signif..), method = "t.test", ref.group = "Flow 0, No Ablation, Light")
  stat_compare_means(comparisons = my_comparisons, label.y = c(4.5,3.5,4), label = "p.signif", hide.ns = TRUE) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  ylim(0,7) +
  scale_y_continuous(breaks=c(0,2,4,6,8))

ggsave("Final Graphs/Simmed_Aligned_Group_Num_in_2_BL.png")

```

### Simulated Turning Bias

```{r}
turning_data_sim <- read.csv("Annushka_Turning_Data_Simmed.csv") %>% 
                           mutate(Flow = ifelse(Flow == "F0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation %in% c("LN","TN"), "No Ablation", ifelse(Ablation == "LY","Ablated",Ablation))) %>%
                           mutate(Darkness = ifelse(Darkness == "DN", "Light", ifelse(Darkness == "DY", "Dark", Darkness))) %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Still Water","Flowing Water (2 BL/s)"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated","Simulated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark","Simulated"))) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep=", "))) %>%
                           mutate(Fish_Num_Ratio = No..Fish.Right/8) %>%
                           mutate(Fish_Ratio = paste(No..Fish.Left,No..Fish.Right,sep=":")) %>%
                           filter(Fish_Ratio %in% c("7:0","6:1","5:2","4:3","3:4","2:5","1:6","0:7")) %>%
                           mutate(Fish_Ratio = fct_relevel(Fish_Ratio,
                                                           c("7:0","6:1","5:2","4:3",
                                                             "3:4","2:5","1:6","0:7"))) %>%
                           mutate(turn_bool = ifelse(Turn.Direction == "right",1,0))

turning_data_sim_sum <- turning_data_sim %>% na.omit %>%
                                     group_by(Fish_Ratio,Fish_Num_Ratio,Flow,Ablation,Darkness,Flow_Ablation_Darkness) %>%
                                     summarize(mean_right_turn = mean(turn_bool),
                                               sd_right_turn = sd(turn_bool),
                                               n = n()) %>%
                                     ungroup()

turning_data_sim_sum_one <- turning_data_sim %>% na.omit %>%
                                     group_by(Fish_Ratio,Fish_Num_Ratio) %>%
                                     summarize(mean_right_turn = mean(turn_bool),
                                               sd_right_turn = sd(turn_bool),
                                               n = n()) %>%
                                     ungroup()
```


```{r}

mi_fr_d_sim <- glm(turn_bool ~ Fish_Num_Ratio * Darkness, data = turning_data_sim, family = binomial)

ggplot(turning_data_sim, aes(x = Fish_Num_Ratio, y = turn_bool, color = Darkness))+
  geom_jitter(alpha = 0.1, height = 0.025)+
  geom_line(aes(x = Fish_Num_Ratio, y = predict(mi_fr_d_sim, type="response"), color = Darkness)) +
  geom_point(aes(x = Fish_Num_Ratio, y = predict(mi_fr_d_sim, type="response"), color = Darkness)) +
  theme_classic() +
  xlab("# Fish on Left : # Fish on Right") +
  ylab("Probability of a Right Turn") +
  scale_colour_manual(values = c(light_ab_color,dark_no_ab_color,sim_color)) +
  scale_x_continuous(breaks = c(0,0.125,0.25,0.375,
                                0.5,0.625,0.75,0.875),
                     labels = c("7:0","6:1","5:2","4:3",
                                "3:4","2:5","1:6","0:7"))

ggsave("Final Graphs/Simmed_Right_Turn_Best_Model.png")

```

