---
title: "NN Alignment Measure"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(ggplot2)
library(bbmle) #For ICtab
library(car)
library(ggpubr)
library(ggdist)
library(emmeans)
library(lme4)
library(circular)
```


```{r}
rad2deg <- function(rad) {(rad * 180) / (pi)}
deg2rad <- function(deg) {(deg * pi) / (180)}
round_any <- function(x, accuracy, f=round){f(x/ accuracy) * accuracy}
ang_mean <- function(x){rad2deg(atan2(mean(sin(deg2rad(x))),mean(cos(deg2rad(x)))))}

fold_angle_0_360_to_0_180 <- function(x){abs(abs(x-180)-180)}

fold_angle_neg_180_180_to_neg_90_90 <- function(x){ifelse(x > 90,90-abs(90-x),ifelse(x < -90, -90+abs(-90-x), x))}

min_n <- function(x,n){sort(x)[1:n]}
max_n <- function(x,n){sort(x,decreasing = TRUE)[1:n]}

light_no_ab_color = "#d4d7dd"
light_ab_color = "#f5ba9e"
dark_no_ab_color = "#5e94d4"
sim_color = "#777777"

flow_split_still = "#F59DE2"
flow_split_flow = "#5DD492"

dark_split_light = "#5e94d4"
dark_split_dark = "#011627"

tailbeat_len = 19

allowed_flow_type = c("Still Water","Flowing Water (2 BL/s)")

dot_binwidth = 0.03
smaller_dot_binwidth = 0.01

text_size = 16
```


```{r}
fish_comp_data <- read.csv("Data/Fish_Comp_Values_3D.csv")  %>% separate(Fish, c("Fish1", "Fish2"),sep="x") %>% mutate(Data_ID = paste(Year,Month,Day,Trial, sep = "_"))

fish_comp_data <- na.omit(fish_comp_data)

fish_comp_data_switch_fish <- fish_comp_data %>% mutate(Fish3 = Fish1,
                                              Fish3_X = Fish1_X,
                                              Fish3_Y = Fish1_Y,
                                              Fish3_Z = Fish1_Z,
                                              Fish3_Speed = Fish1_Speed) %>%
                                       mutate(Fish1 = Fish2,
                                              Fish1_X = Fish2_X,
                                              Fish1_Y = Fish2_Y,
                                              Fish1_Z = Fish2_Z,
                                              Fish1_Speed = Fish2_Speed) %>%
                                       mutate(Fish2 = Fish3,
                                              Fish2_X = Fish3_X,
                                              Fish2_Y = Fish3_Y,
                                              Fish2_Z = Fish3_Z,
                                              Fish2_Speed = Fish3_Speed) %>%
                                       select(-c(Fish3,Fish3_X,Fish3_Y,Fish3_Z,Fish3_Speed))

fish_comp_data_combo <- bind_rows(fish_comp_data, fish_comp_data_switch_fish)

fish_comp_data_combo <- fish_comp_data_combo %>% mutate(Flow = ifelse(Flow == "0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation == "N", "No Ablation", "Ablated")) %>%
                           mutate(Darkness = ifelse(Darkness == "N", "Light", "Dark")) %>%
                           filter(Fish1_Speed <= 5) %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Still Water","Flowing Water (2 BL/s)"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark"))) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep="/n")))

fish_data_nn <- fish_comp_data_combo %>% group_by(Fish1,Tailbeat_Num,Data_ID) %>%
                                    mutate(nndDistance = min(Distance, na.rm = TRUE),
                                           nndDistance = ifelse(is.infinite(nndDistance), NA, nndDistance),
                                           all_nas = all(is.na(nndDistance))) %>%
                                    filter(Distance == nndDistance | all_nas) %>%
                                    mutate(row_n = row_number()) %>%
                                    filter(row_n == 1) %>%
                                    ungroup() %>%
                                    group_by(Flow_Ablation_Darkness) %>%
                                    mutate(Mean_Heading_Diff = mean(Yaw.Heading_Diff), SD_Heading_Diff = sd(Yaw.Heading_Diff)) %>%
                                    ungroup() %>%
  
                          # ### Used to remove every third point to reduce autocorrelation
                           mutate(Date_Trial_Fish = paste(Year,Month,Day,Trial,Fish1,sep="_")) %>%
                           group_by(Date_Trial_Fish) %>%
                           filter(row_number() %% 3 == 1) %>%
                           ungroup()
                           # ###
```

```{r}

fish_data_nn_polar <- fish_data_nn %>% filter(Yaw.Heading_Diff <= 90) %>%
                                        mutate(Round_Yaw.Heading_Diff = round_any(Yaw.Heading_Diff,15)) %>%
                                       group_by(Round_Yaw.Heading_Diff, Flow, Ablation, Darkness) %>%
                                       summarise(count_headings = n()) %>%
                                       ungroup() %>%
                                       group_by(Flow, Ablation, Darkness) %>%
                                       mutate(sum_count = sum(count_headings),
                                              percent_dist = count_headings / sum_count) %>%
                                       ungroup()

ggplot(fish_data_nn_polar %>% filter(Flow == "Still Water"),
       aes(x = Round_Yaw.Heading_Diff, y = percent_dist, fill = interaction(Ablation,Darkness,sep=", "))) +
  geom_col() +
  facet_wrap(~interaction(Ablation,Darkness,sep=", "))+
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  coord_polar() +
  scale_x_continuous(limits = c(0,359),
                     breaks = seq(0, 360, by = 45),
                     minor_breaks = seq(0, 360, by = 15)) +
  theme_light()+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size = text_size),
        axis.text.y = element_text(size = text_size),
        axis.title.y = element_text(size = text_size))



ggplot(fish_data_nn_polar %>% filter(Flow == "Flowing Water (2 BL/s)"),
       aes(x = Round_Yaw.Heading_Diff, y = percent_dist, fill = interaction(Ablation,Darkness,sep=", "))) +
  geom_col() +
  facet_wrap(~interaction(Ablation,Darkness,sep=", "))+
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  coord_polar() +
  scale_x_continuous(limits = c(0,359),
                     breaks = seq(0, 360, by = 45),
                     minor_breaks = seq(0, 360, by = 15)) +
  theme_light()+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size = text_size),
        axis.text.y = element_text(size = text_size),
        axis.title.y = element_text(size = text_size))

still_fish_data_nn <- fish_data_nn %>% filter(Flow == "Still Water")

#Non circular stats
heading_diff_glmer_still <- glmer(Yaw.Heading_Diff ~ Ablation*Darkness + (1|Data_ID), data = fish_data_nn %>% filter(Flow == "Still Water"), family = gaussian())
Anova(heading_diff_glmer_still)

heading_diff_glmer_flow <- glmer(Yaw.Heading_Diff ~ Ablation*Darkness + (1|Data_ID), data = fish_data_nn %>% filter(Flow == "Flowing Water (2 BL/s)"), family = gaussian())
Anova(heading_diff_glmer_flow)


```

```{r}

#Aligned where heading difference is less than 45 degrees

fish_aligned_2BL <- fish_comp_data_combo %>% filter(Distance <= 2 & Yaw.Heading_Diff <= 30) %>%
                    select(c(Data_ID, Year, Month, Day, Trial, Flow, Ablation, Darkness, Fish1, Fish2, Tailbeat_Num, Distance, Yaw.Heading_Diff)) %>%
                    arrange(Year, Month, Day, Trial, Fish1, Fish2, Tailbeat_Num) %>%
                    group_by(Data_ID, Year, Month, Day, Trial, Flow, Ablation, Darkness, Fish1, Fish2) %>%
                    mutate(Counter = 1,
                           Sum_Counter = cumsum(Counter),
                           Tailbeat_Diff = Tailbeat_Num - lag(Tailbeat_Num),
                           Tailbeat_Diff = ifelse(is.na(Tailbeat_Diff), 1, Tailbeat_Diff),
                           Sum_Tailbeat_Diff = cumsum(Tailbeat_Diff),
                           Alignment_Grouping = Sum_Tailbeat_Diff - Sum_Counter) %>%
                    ungroup() %>%
                    group_by(Data_ID, Year, Month, Day, Trial, Flow, Ablation, Darkness, Fish1, Fish2, Alignment_Grouping) %>%
                    summarise(Aligned_2BL_Dur = n()) %>%
                    ungroup() %>%
                    group_by(Flow, Ablation, Darkness) %>%
                    mutate(Mean_Aligned_2BL_Dur = mean(Aligned_2BL_Dur), SD_Aligned_2BL_Dur = sd(Aligned_2BL_Dur)) %>%
                    ungroup()

fish_aligned_2BL %>% group_by(Flow, Ablation, Darkness) %>% summarise(N = n())

```

```{r}
aligned_2BL_still <- ggplot(fish_aligned_2BL %>% filter(Flow == "Still Water"),
       aes(x = interaction(Ablation,Darkness,sep=", "), y = Aligned_2BL_Dur,
           color = interaction(Ablation,Darkness,sep=", "),
           fill = interaction(Ablation,Darkness,sep=", ")))+
  stat_dots(side = "both", binwidth = unit(smaller_dot_binwidth, "npc")) +
  geom_point(aes(y = Mean_Aligned_2BL_Dur), size = 5, color = "Black") +
  geom_errorbar(aes(ymin=Mean_Aligned_2BL_Dur-SD_Aligned_2BL_Dur, ymax=Mean_Aligned_2BL_Dur+SD_Aligned_2BL_Dur), width=.2, color = "Black")+
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  scale_color_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  #ggtitle("Effect of Available Senses on Nearest Neighbor Distance (NND) in Still Water") +
  xlab("") +
  ylab("Number of Tailbeats Aligned") +
  theme_light()+ 
  theme(legend.position = "none") +
  #stat_compare_means(comparisons = my_comparisons, label.y = c(1.75), label = "p.signif", hide.ns = TRUE) +
  theme(axis.text.x = element_text(size = text_size),
        axis.text.y = element_text(size = text_size),
        axis.title.y = element_text(size = text_size))+
  scale_x_discrete(labels=function(x){sub(",\\s", "\n", x)})

my_comparisons <- list()

aligned_2BL_flow <- ggplot(fish_aligned_2BL %>% filter(Flow == "Flowing Water (2 BL/s)"),
       aes(x = interaction(Ablation,Darkness,sep=", "), y = Aligned_2BL_Dur,
           color = interaction(Ablation,Darkness,sep=", "),
           fill = interaction(Ablation,Darkness,sep=", ")))+
  stat_dots(side = "both", binwidth = unit(smaller_dot_binwidth, "npc")) +
  geom_point(aes(y = Mean_Aligned_2BL_Dur), size = 5, color = "Black") +
  geom_errorbar(aes(ymin=Mean_Aligned_2BL_Dur-SD_Aligned_2BL_Dur, ymax=Mean_Aligned_2BL_Dur+SD_Aligned_2BL_Dur), width=.2, color = "Black")+
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  scale_color_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  #ggtitle("Effect of Available Senses on Nearest Neighbor Distance (NND) in Still Water") +
  xlab("") +
  ylab("Number of Tailbeats Aligned") +
  theme_light()+ 
  theme(legend.position = "none") +
  #stat_compare_means(comparisons = my_comparisons, label.y = c(1.75), label = "p.signif", hide.ns = TRUE) +
  theme(axis.text.x = element_text(size = text_size),
        axis.text.y = element_text(size = text_size),
        axis.title.y = element_text(size = text_size))+
  scale_x_discrete(labels=function(x){sub(",\\s", "\n", x)})


aligned_2BL_still
aligned_2BL_flow

aligned_2BL_glmer_still <- glmer(Aligned_2BL_Dur ~ Ablation*Darkness + (1|Data_ID),
                                 data = fish_aligned_2BL %>% filter(Flow == "Still Water"),
                                 family = poisson())
Anova(aligned_2BL_glmer_still)

aligned_2BL_glmer_flow <- glmer(Aligned_2BL_Dur ~ Ablation*Darkness + (1|Data_ID), 
                                data = fish_aligned_2BL %>% filter(Flow == "Flowing Water (2 BL/s)"),
                                family = poisson())
Anova(aligned_2BL_glmer_flow)

```

Okay so I think fish in darkness are paying attention to less fish
Only responding to turns when one or two other fish do, and more apart in time. 

Look at delays in fish turning 
NN Heading might obscure some things as they pair up again soon after


```{r}

aligned_fish_comp <- fish_comp_data_combo %>% filter(Yaw.Heading_Diff <= 15) %>% filter(Flow == "Still Water") %>%
                    group_by(Flow, Ablation, Darkness) %>%
                    mutate(Mean_Distance = mean(Distance), SD_Distance = sd(Distance)) %>%
                    ungroup()

close_fish_comp <- fish_comp_data_combo %>% filter(Distance <= 2) %>% filter(Flow == "Still Water") %>%
                    group_by(Flow, Ablation, Darkness) %>%
                    mutate(Mean_Heading = mean(Yaw.Heading_Diff), SD_Heading = sd(Yaw.Heading_Diff)) %>%
                    ungroup()

ggplot(aligned_fish_comp %>% filter(Flow == "Still Water"),
       aes(x = interaction(Ablation,Darkness,sep=", "), y = Distance,
           color = interaction(Ablation,Darkness,sep=", "),
           fill = interaction(Ablation,Darkness,sep=", ")))+
  stat_dots(side = "both", binwidth = unit(smaller_dot_binwidth, "npc")) +
  geom_point(aes(y = Mean_Distance), size = 5, color = "Black") +
  geom_errorbar(aes(ymin=Mean_Distance-SD_Distance, ymax=Mean_Distance+SD_Distance), width=.2, color = "Black")+
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  scale_color_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  #ggtitle("Effect of Available Senses on Nearest Neighbor Distance (NND) in Still Water") +
  xlab("") +
  ylab("Distance (BL)") +
  theme_light()+ 
  theme(legend.position = "none") +
  #stat_compare_means(comparisons = my_comparisons, label.y = c(1.75), label = "p.signif", hide.ns = TRUE) +
  theme(axis.text.x = element_text(size = text_size),
        axis.text.y = element_text(size = text_size),
        axis.title.y = element_text(size = text_size))+
  scale_x_discrete(labels=function(x){sub(",\\s", "\n", x)})

Aligned_Distance_glmer_still <- lmer(Distance ~ Ablation*Darkness + (1|Data_ID),
                                 data = aligned_fish_comp %>% filter(Flow == "Still Water"))

Anova(Aligned_Distance_glmer_still)


ggplot(close_fish_comp %>% filter(Flow == "Still Water"),
       aes(x = interaction(Ablation,Darkness,sep=", "), y = Yaw.Heading_Diff,
           color = interaction(Ablation,Darkness,sep=", "),
           fill = interaction(Ablation,Darkness,sep=", ")))+
  stat_dots(side = "both", binwidth = unit(smaller_dot_binwidth, "npc")) +
  geom_point(aes(y = Mean_Heading), size = 5, color = "Black") +
  geom_errorbar(aes(ymin=Mean_Heading-SD_Heading, ymax=Mean_Heading+SD_Heading), width=.2, color = "Black")+
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  scale_color_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color)) +
  #ggtitle("Effect of Available Senses on Nearest Neighbor Distance (NND) in Still Water") +
  xlab("") +
  ylab("Distance (BL)") +
  theme_light()+ 
  theme(legend.position = "none") +
  #stat_compare_means(comparisons = my_comparisons, label.y = c(1.75), label = "p.signif", hide.ns = TRUE) +
  theme(axis.text.x = element_text(size = text_size),
        axis.text.y = element_text(size = text_size),
        axis.title.y = element_text(size = text_size))+
  scale_x_discrete(labels=function(x){sub(",\\s", "\n", x)})

Close_Heading__glmer_still <- lmer(Yaw.Heading_Diff ~ Ablation*Darkness + (1|Data_ID),
                                 data = close_fish_comp %>% filter(Flow == "Still Water"))

Anova(Close_Heading__glmer_still)

```

