---
title: "NN_Accel_Heading"
format: html
editor: visual
---

## Loading in the Libraries for Everything
```{r}
library(MASS)
library(tidyverse)
library(ggplot2)
library(bbmle) #For ICtab
library(car)
library(ggpubr)
library(ggdist)
library(emmeans)
library(lme4)
library(viridis)
```


```{r}
rad2deg <- function(rad) {(rad * 180) / (pi)}
deg2rad <- function(deg) {(deg * pi) / (180)}
round_any <- function(x, accuracy, f=round){f(x/ accuracy) * accuracy}
ang_mean <- function(x){rad2deg(atan2(mean(sin(deg2rad(x))),mean(cos(deg2rad(x)))))}

fold_angle_0_360_to_0_180 <- function(x){abs(abs(x-180)-180)}

fold_angle_neg_180_180_to_neg_90_90 <- function(x){ifelse(x > 90,90-abs(90-x),ifelse(x < -90, -90+abs(-90-x), x))}

min_n <- function(x,n){sort(x)[1:n]}
max_n <- function(x,n){sort(x,decreasing = TRUE)[1:n]}

light_no_ab_color = "#d4d7dd"
light_ab_color = "#f5ba9e"
dark_no_ab_color = "#5e94d4"
dark_ab_color = "#1E4371"
sim_color = "#777777"

flow_split_still = "#F59DE2"
flow_split_flow = "#5DD492"

dark_split_light = "#5e94d4"
dark_split_dark = "#011627"

tailbeat_len = 19

allowed_flow_type = c("Still Water","Flowing Water (2 BL/s)")

dot_binwidth = 0.03

text_size = 16
```

Load in the data

```{r}

fish_comp_data <- read.csv("Data/Fish_Comp_Values_3D.csv") %>%
                           mutate(Flow = ifelse(Flow == "0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation  == "N", "No Ablation", "Ablated")) %>%
                           mutate(Darkness = ifelse(Darkness == "N", "Light", "Dark")) %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Still Water","Flowing Water (2 BL/s)"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark"))) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep=", "))) %>%
                           separate(Fish, c("Fish1", "Fish2"),sep="x") %>% 
                           mutate(Data_ID = paste(Year,Month,Day,Trial, sep = "_"))
                           
fish_comp_data <- na.omit(fish_comp_data)

fish_comp_data_switch_fish <- fish_comp_data %>% mutate(Fish3 = Fish1,
                                              Fish3_X = Fish1_X,
                                              Fish3_Y = Fish1_Y,
                                              Fish3_Z = Fish1_Z,
                                              Fish3_Speed = Fish1_Speed,
                                              Fish3_Accel = Fish1_Accel,
                                              Fish3_Yaw_Heading = Fish1_Yaw_Heading,
                                              Fish3_Yaw_Heading_PS = Fish1_Yaw_Heading_PS
                                              ) %>%
                                       mutate(Fish1 = Fish2,
                                              Fish1_X = Fish2_X,
                                              Fish1_Y = Fish2_Y,
                                              Fish1_Z = Fish2_Z,
                                              Fish1_Speed = Fish2_Speed,
                                              Fish1_Accel = Fish2_Accel,
                                              Fish1_Yaw_Heading = Fish2_Yaw_Heading,
                                              Fish1_Yaw_Heading_PS = Fish2_Yaw_Heading_PS) %>%
                                       mutate(Fish2 = Fish3,
                                              Fish2_X = Fish3_X,
                                              Fish2_Y = Fish3_Y,
                                              Fish2_Z = Fish3_Z,
                                              Fish2_Speed = Fish3_Speed,
                                              Fish2_Accel = Fish3_Accel,
                                              Fish2_Yaw_Heading = Fish3_Yaw_Heading,
                                              Fish2_Yaw_Heading_PS = Fish3_Yaw_Heading_PS) %>%
                                       #Switch around angle when we switch focal fish
                                       mutate(Angle = ifelse(Angle < 0, Angle + 180, Angle - 180),
                                              Relative_X = -1*Relative_X) %>%
                                       select(-c(Fish3,Fish3_X,Fish3_Y,Fish3_Z,Fish3_Speed,Fish3_Accel,Fish3_Yaw_Heading,Fish3_Yaw_Heading_PS))

fish_comp_data_combo <- bind_rows(fish_comp_data, fish_comp_data_switch_fish)


fish_data_nn <- fish_comp_data_combo %>% group_by(Fish1,Tailbeat_Num,Data_ID) %>%
                                    mutate(nndDistance = min(Distance, na.rm = TRUE),
                                           nndDistance = ifelse(is.infinite(nndDistance), NA, nndDistance),
                                           all_nas = all(is.na(nndDistance))) %>%
                                    filter(Distance == nndDistance | all_nas) %>%
                                    mutate(row_n = row_number()) %>%
                                    filter(row_n == 1) %>%
                                    ungroup() %>%
                                    mutate(Angle_Rads = deg2rad(Angle),
                                           Fish1_Yaw_Heading_PS = deg2rad(Fish1_Yaw_Heading_PS)) %>%
                                    filter(Distance <= 2)


nn_heading_sum <- fish_data_nn %>% mutate(angle_bins = round_any(Angle_Rads,pi/8)) %>%
                                                group_by(angle_bins,Flow,Ablation,Darkness,Flow_Ablation_Darkness) %>%
                                                summarise(mean_turn = mean(Fish1_Yaw_Heading_PS, na.rm = T),
                                                          sd_turn = sd(Fish1_Yaw_Heading_PS, na.rm = T),
                                                          n = n()) %>%
                                                ungroup() %>%
                                                na.omit()

nn_accel_sum <- fish_data_nn %>% mutate(distance_bins = round_any(Relative_X,0.25)) %>%
                                                group_by(distance_bins,Flow,Ablation,Darkness,Flow_Ablation_Darkness) %>%
                                                summarise(mean_accel = mean(Fish1_Accel, na.rm = T),
                                                          sd_accel = sd(Fish1_Accel, na.rm = T),
                                                          n = n()) %>%
                                                ungroup() %>%
                                                na.omit()
                           
```



```{r}

fish_data_nn_model <- fish_data_nn %>% filter(Flow == "Still Water") %>% 
                                       mutate(AblationCat = ifelse(Ablation == "Ablated",1,0),
                                              DarknessCat = ifelse(Darkness == "Dark",1,0))

heading_ps_angle_base <- lm(Fish1_Yaw_Heading_PS ~ 1, data = fish_data_nn_model) 

heading_ps_angle_step <- stepAIC(heading_ps_angle_base,
                                   list(upper = ~ ((cos(Angle_Rads)+sin(Angle_Rads))*Ablation*Darkness), lower = ~1),
                                   direction = "both",
                                   trace = F)

Anova(heading_ps_angle_step)

tester_model <- lm(Fish1_Yaw_Heading_PS ~ sin(Angle_Rads)*Ablation*Darkness, data = fish_data_nn_model) 
Anova(tester_model)

ggplot(fish_data_nn %>% filter(Flow == "Still Water"),
       aes(x = Angle_Rads, y = Fish1_Yaw_Heading_PS, color = interaction(Ablation, Darkness, sep =", ")))+
  geom_point(alpha = 0.1)+
  facet_wrap(~ interaction(Ablation, Darkness, sep =", ")) +
  #geom_smooth(se = F)+
  geom_smooth(se = F, method = glm, formula = y ~ 1)+
  #geom_line(aes(y = predict(heading_ps_angle_step)), size = 1)+
  theme_classic() +
  #ylim(-5,5)+
  xlab("direction of neighbour (degrees)") +
  ylab("focal fish turning angle (rad/sec)") +
  scale_colour_manual(values = c(light_no_ab_color,light_ab_color,dark_no_ab_color,dark_ab_color)) +
  scale_x_continuous(breaks = unique(nn_heading_sum$angle_bins),
                     labels = rad2deg(unique(nn_heading_sum$angle_bins))) +
  labs(color = "Sensory Conditions")

ggplot(nn_heading_sum %>% filter(Flow == "Still Water"),
       aes(x = angle_bins, y = rad2deg(mean_turn), color = interaction(Ablation, Darkness, sep =", ")))+
  geom_point()+
  #geom_smooth(se = F)+
  #geom_line(aes(y = sin_pred)) +
  #geom_line(alpha = 0.75) +
  #geom_smooth(se = F, method = glm, formula = y ~ sin(x))+
  geom_line(aes(y = rad2deg(predict(heading_ps_angle_step,
                    newdata = nn_heading_sum %>% filter(Flow == "Still Water") %>% mutate(Angle_Rads = angle_bins)))), size = 1)+
  theme_classic() +
  #ylim(-0.6,0.6)+
  xlab("direction of neighbour (degrees)") +
  ylab("focal fish turning angle (degrees/sec)") +
  scale_colour_manual(values = c(light_no_ab_color,light_ab_color,dark_no_ab_color,dark_ab_color)) +
  scale_x_continuous(breaks = unique(nn_heading_sum$angle_bins),
                     labels = rad2deg(unique(nn_heading_sum$angle_bins))) +
  # scale_x_continuous(breaks = unique(nn_heading_sum$angle_bins),
  #                    labels = c("-π","-3π/4","-π/2","-π/4","0","π/4","π/2","3π/4","π"))+
  labs(color = "Sensory Conditions")

```

```{r}

accel_base_lm <- lm(Fish1_Accel ~ Flow_Ablation_Darkness, data = fish_data_nn %>% filter(Flow == "Still Water"))
accel_lin_lm <- lm(Fish1_Accel ~ Relative_X*Flow_Ablation_Darkness, data = fish_data_nn %>% filter(Flow == "Still Water"))

AIC(accel_base_lm,accel_lin_lm) %>% arrange(AIC)

Anova(accel_base_lm)

ggplot(fish_data_nn %>% filter(Flow == "Still Water"),
       aes(x = Relative_X, y = Fish1_Accel, color = interaction(Ablation, Darkness, sep =", ")))+
  geom_point(alpha = 0.1)+
  facet_wrap(~ interaction(Ablation, Darkness, sep =", ")) +
  geom_smooth(se = F, method = glm, formula = y ~ x)+
  theme_classic() +
  xlab("distance from neighbour (BL)") +
  ylab("focal fish acceleration (BL/s^2)") +
  #ylim(-0.01, 0.01) +
  scale_colour_manual(values = c(light_no_ab_color,light_ab_color,dark_no_ab_color,dark_ab_color)) +
  labs(color = "Sensory Conditions")

ggplot(nn_accel_sum %>% filter(Flow == "Still Water" & distance_bins < 3),
       aes(x = distance_bins, y = mean_accel, color = interaction(Ablation, Darkness, sep =", ")))+
  geom_point()+
  #geom_line(alpha = 0.75) +
  geom_smooth(se = F, method = glm, formula = y ~ 1)+
  theme_classic() +
  xlab("distance from neighbour (BL)") +
  ylab("focal fish acceleration (BL/s^2)") +
  scale_colour_manual(values = c(light_no_ab_color,light_ab_color,dark_no_ab_color,dark_ab_color)) +
  labs(color = "Sensory Conditions")

```

```{r}

directional_df <- fish_data_nn %>% mutate(round_X = round_any(RelativeX,0.5),
                                                    round_Y = round_any(RelativeY,0.5)) %>%
                                                      group_by(round_X,round_Y,Flow,Ablation,Darkness,Flow_Ablation_Darkness) %>%
                                                      summarise(mean_accel = mean(Fish1_Accel),
                                                                mean_turn = mean(Fish1_Yaw_Heading_PS),
                                                                n = n()) %>%
                                                      ungroup()

ggplot(directional_df %>% filter(Flow == "Still Water" & n > 5 & mean_accel > -0.01 & mean_accel < 0.01),
       aes(round_X, round_Y, fill= mean_accel)) + 
  geom_tile()+
  facet_wrap(~Flow_Ablation_Darkness)+
  scale_fill_viridis(option="magma")+
  coord_fixed()+
  theme_classic()


ggplot(directional_df %>% filter(Flow == "Still Water" & n > 5),
       aes(round_X, round_Y, fill= mean_turn)) + 
  geom_tile()+
  facet_wrap(~Flow_Ablation_Darkness)+
  scale_fill_viridis(option="magma")+
  coord_fixed()+
  theme_classic()


```

