---
title: "Fish Whole School Data"
output: html_notebook
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(car)
library(viridis)
library(boot)
library(mgcv)
library(forcats)
library(ggpubr)
```

Sets up the functions that will be used later 
```{r}
rad2deg <- function(rad) {(rad * 180) / (pi)}
deg2rad <- function(deg) {(deg * pi) / (180)}
round_any <- function(x, accuracy, f=round){f(x/ accuracy) * accuracy}
ang_mean <- function(x){rad2deg(atan(mean(sin(deg2rad(x)))/mean(cos(deg2rad(x)))))}

fold_angle_0_360_to_0_180 <- function(x){abs(abs(x-180)-180)}

fold_angle_neg_180_180_to_neg_90_90 <- function(x){ifelse(x > 90,90-abs(90-x),ifelse(x < -90, -90+abs(-90-x), x))}

min_n <- function(x,n){sort(x)[1:n]}
max_n <- function(x,n){sort(x,decreasing = TRUE)[1:n]}
```

Reads in the data and alters it as needed 
```{r}
comp_data <- read.csv("Fish_Comp_Values.csv")
comp_data <- na.omit(comp_data)

comp_data <- comp_data %>% mutate(Flow = ifelse(Flow == "0", "Flow 0", "Flow 2")) %>%
                           mutate(Ablation = ifelse(Ablation == "N", "No Ablation", "Ablated")) %>%
                           mutate(Darkness = ifelse(Darkness == "N", "Light", "Dark")) %>%
                           filter(Distance <= 4) %>%
                           filter(abs(Speed_Diff) <= 6) %>% 
                           mutate(Speed_Diff = abs(Speed_Diff)) %>%
                           mutate(fold_heading_diff = abs(fold_angle_neg_180_180_to_neg_90_90(Heading_Diff))) %>%
                           mutate(Is_Aligned = ifelse(Heading_Diff < 30, 1, 0)) %>%
                           mutate(Is_Reversed = ifelse(Heading_Diff > 150, 1, 0)) %>%
                           separate(Fish, c("Fish1", "Fish2"),sep="x") %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Flow 0","Flow 2"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark"))) %>%
                           mutate(rad_Angle = Angle) %>%
                           mutate(sin_Angle = sin(rad_Angle), cos_Angle = cos(rad_Angle)) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep=", ")))
                           
                           #mutate(Angle = fold_angle_0_360_to_0_180(Angle))

sum_comp_data <- comp_data %>% mutate(X_Distance = round_any(X_Distance,0.25), 
                                      Y_Distance = round_any(abs(Y_Distance),0.25)) %>%
                               group_by(Flow,Ablation,Darkness,X_Distance,Y_Distance) %>%
                               summarise(Speed_Diff = mean(Speed_Diff),
                                         Heading_Diff = ang_mean(Heading_Diff),
                                         Sync = mean(Sync),
                                         Fold_Heading_Diff = mean(fold_heading_diff),
                                         Is_Aligned = mean(Is_Aligned),
                                         Is_Reversed = mean(Is_Reversed))

comp_data_switch_fish <- comp_data %>% mutate(Fish3 = Fish1) %>%
                                       mutate(Fish1 = Fish2) %>%
                                       mutate(Fish2 = Fish3) %>%
                                       select(-c(Fish3))

comp_data_NND <- bind_rows(comp_data, comp_data_switch_fish) %>% group_by(Year,Month,Day,Trial,Fish1,Tailbeat.Num) %>%
                                                                 filter(Distance == min(Distance)) %>%
                                                                 ungroup()

comp_data_near_3 <- bind_rows(comp_data, comp_data_switch_fish) %>% group_by(Year,Month,Day,Trial,Fish1,Tailbeat.Num) %>%
                                                                 slice_min(Distance, n = 3) %>%
                                                                 ungroup() %>%
                                                                 distinct(Distance, .keep_all= TRUE)
```